---
kind: pipeline
name: default

steps:
  - name: lint
    image: golang
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.0
      - golangci-lint run --enable-all
